// ============================================================
// 静态词典：仅用于"用户中文输入 → 英文 query"的反向映射（零延迟）。
// 注意：宝可梦/属性/招式的「显示中文」一律取 PokeAPI 官方 zh-hans，不靠此表。
// 词典未命中 → fallback：把原 query 交给 PokeAPI 直查（小模型也可直接输出英文名）。
// ============================================================

/** 常见宝可梦中文名 → 英文 id（覆盖热门，未命中走 fallback） */
export const POKEMON_ZH_TO_EN: Record<string, string> = {
  皮卡丘: 'pikachu',
  雷丘: 'raichu',
  小火龙: 'charmander',
  火恐龙: 'charmeleon',
  喷火龙: 'charizard',
  杰尼龟: 'squirtle',
  卡咪龟: 'wartortle',
  水箭龟: 'blastoise',
  妙蛙种子: 'bulbasaur',
  妙蛙草: 'ivysaur',
  妙蛙花: 'venusaur',
  伊布: 'eevee',
  水伊布: 'vaporeon',
  雷伊布: 'jolteon',
  火伊布: 'flareon',
  太阳伊布: 'espeon',
  月亮伊布: 'umbreon',
  叶伊布: 'leafeon',
  冰伊布: 'glaceon',
  仙子伊布: 'sylveon',
  超梦: 'mewtwo',
  梦幻: 'mew',
  快龙: 'dragonite',
  迷你龙: 'dratini',
  哈克龙: 'dragonair',
  暴鲤龙: 'gyarados',
  鲤鱼王: 'magikarp',
  耿鬼: 'gengar',
  鬼斯: 'gastly',
  鬼斯通: 'haunter',
  卡比兽: 'snorlax',
  胖丁: 'jigglypuff',
  可达鸭: 'psyduck',
  小拳石: 'geodude',
  隆隆石: 'graveler',
  隆隆岩: 'golem',
  大岩蛇: 'onix',
  六尾: 'vulpix',
  九尾: 'ninetales',
  走路草: 'oddish',
  臭臭花: 'gloom',
  霸王花: 'vileplume',
  地鼠: 'diglett',
  三地鼠: 'dugtrio',
  超音蝠: 'zubat',
  大嘴蝠: 'golbat',
  穿山鼠: 'sandshrew',
  穿山王: 'sandslash',
  尼多兰: 'nidoran-f',
  尼多朗: 'nidoran-m',
  比卡丘: 'pikachu',
  风速狗: 'arcanine',
  卡蒂狗: 'growlithe',
  化石翼龙: 'aerodactyl',
  乘龙: 'lapras',
  拉普拉斯: 'lapras',
  快泳蛙: 'poliwrath',
  蚊香蝌蚪: 'poliwag',
  闪电鸟: 'zapdos',
  急冻鸟: 'articuno',
  火焰鸟: 'moltres',
  袋龙: 'kangaskhan',
  大葱鸭: 'farfetchd',
  椰蛋树: 'exeggutor',
  嘎啦嘎啦: 'marowak',
  沙瓦郎: 'hitmonlee',
  艾比郎: 'hitmonchan',
  铁甲犀牛: 'rhyhorn',
  钻角犀兽: 'rhydon',
  吉利蛋: 'chansey',
  蔓藤怪: 'tangela',
  吸盘魔偶: 'mr-mime',
  飞天螳螂: 'scyther',
  凯罗斯: 'pinsir',
  肯泰罗: 'tauros',
  拉达: 'raticate',
  小拉达: 'rattata',
  波波: 'pidgey',
  比比鸟: 'pidgeotto',
  大比鸟: 'pidgeot',
  绿毛虫: 'caterpie',
  独角虫: 'weedle',
  巴大蝶: 'butterfree',
  大针蜂: 'beedrill',
  大舌头: 'lickitung',
  大食花: 'victreebel',
  喇叭芽: 'bellsprout',
  毽子花: 'jumpluff',
  火球鼠: 'cyndaquil',
  巨钳螳螂: 'scizor',
  班吉拉: 'tyranitar',
  幼基拉斯: 'larvitar',
  路卡利欧: 'lucario',
  利欧路: 'riolu',
  烈咬陆鲨: 'garchomp',
  圆陆鲨: 'gible',
  甲贺忍蛙: 'greninja',
  叽喳鸡: 'fletchling',
  火爆猴: 'primeape',
  猴怪: 'mankey',
  小磁怪: 'magnemite',
  三合一磁怪: 'magneton',
};

/** 属性中文 → 英文（用户输入"火克什么"→ fire） */
export const TYPE_ZH_TO_EN: Record<string, string> = {
  一般: 'normal', 普通: 'normal',
  火: 'fire', 火系: 'fire',
  水: 'water', 水系: 'water',
  电: 'electric', 电系: 'electric',
  草: 'grass', 草系: 'grass',
  冰: 'ice', 冰系: 'ice',
  格斗: 'fighting', 战斗: 'fighting',
  毒: 'poison',
  地面: 'ground',
  飞行: 'flying',
  超能力: 'psychic', 超能: 'psychic',
  虫: 'bug',
  岩石: 'rock', 岩: 'rock',
  幽灵: 'ghost', 鬼: 'ghost',
  龙: 'dragon',
  恶: 'dark', 黑暗: 'dark',
  钢: 'steel',
  妖精: 'fairy', 仙: 'fairy',
};

/** 把用户输入归一为英文 query：先查词典，命中返回英文，否则原样返回 */
export function resolvePokemonQuery(input: string): string {
  const trimmed = input.trim();
  if (POKEMON_ZH_TO_EN[trimmed]) return POKEMON_ZH_TO_EN[trimmed];
  // 直接是英文/数字 → 小写化交给 PokeAPI
  return trimmed.toLowerCase().replace(/\s+/g, '-');
}

export function resolveTypeQuery(input: string): string {
  const trimmed = input.trim();
  if (TYPE_ZH_TO_EN[trimmed]) return TYPE_ZH_TO_EN[trimmed];
  return trimmed.toLowerCase();
}
